[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "sh -c 'mkdir -p /tmp/keycloak-tx-object-store && /opt/keycloak/bin/kc.sh start --optimized'"
  healthcheckPath = "/health/ready"
  healthcheckTimeout = 300
