[build]
  builder = "DOCKERFILE"
  dockerfilePath = "Dockerfile"

[deploy]
  startCommand = "/opt/keycloak/bin/kc.sh start-dev --http-port=8080 --hostname-strict=false"
  healthcheckPath = "/health/ready"
  healthcheckTimeout = 300
